all: main

main: main.c randnum.c randnum.h quicksort.c quicksort.h partition.c partition.h
	gcc main.c randnum.c randnum.h quicksort.c quicksort.h partition.c partition.h -o a.out
clean:
	rm -f a.out sortnumber.txt number.txt
