all: main

main: maineng.c heapsort.c heapsort.h heapify.c heapify.h swap.c swap.h randeng.c randeng.h
	gcc maineng.c randeng.c randeng.h heapsort.c heapsort.h heapify.c heapify.h swap.c swap.h -o a.out
clean:
	rm -f a.out sortnumber.txt number.txt
