all: main

main: main.c heapsort.c heapsort.h heapify.c heapify.h swap.c swap.h randnum.c randnum.h
	gcc main.c randnum.c randnum.h heapsort.c heapsort.h heapify.c heapify.h swap.c swap.h -o a.out
clean:
	rm -f a.out sortnumber.txt number.txt
