all: main

main: maineng.c randeng.c randeng.h mergesort.c mergesort.h merge.c merge.h
	gcc maineng.c randeng.c randeng.h mergesort.c mergesort.h merge.c merge.h -o a.out
clean:
	rm -f a.out sortwords.txt words.txt
