all: main

main: main.c randnum.c randnum.h mergesort.c mergesort.h merge.c merge.h
	gcc mergesort.c merge.h main.c randnum.c randnum.h merge.c merge.h -o a.out
clean:
	rm -f a.out sortnumber.txt number.txt
